
name: Run Selenium On GitHub Action
on:
  push

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Installing package list
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade webdriver_manager
          pip install -r requirements.txt    
      
      - name: Install plugin
        run: pip install pytest-github-actions-annotate-failures 
      
      - name: Running the Python script
        run: pytest -v -s --alluredir=./Logs testCases/testGoogleSearch.py


      - name: Allure results
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: Logs
          allure_report: allure-report 
          gh_pages: gh_pages
          allure_history: allure-history
          
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PASS_TOKEN }}
          PUBLISH_BRANCH: gh_pages
          PUBLISH_DIR: allure-history
      

