name: Python Selenium CI Tests
'on':
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Install ChromeDriver
        run: >
          LATEST=$(wget -q -O -
          http://chromedriver.storage.googleapis.com/LATEST_RELEASE)

          wget
          http://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip

          unzip chromedriver_linux64.zip

          chmod +x chromedriver

          sudo mv chromedriver /usr/local/bin

      - name: Install ChromeDriver
        run: |
          LATEST=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget http://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin
      
      - name: Run tests
        run: |
          pytest --alluredir=./Reports testCases/testGoogleSearch.py
      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: ./Reports
